git config user.name "alexdinisor98";
git config user.email "alexandra_dinisor@yahoo.com";
git fetch;
git checkout -f master;
git reset;
cp -f target/addon.xml build;
git add build/addon.xml;
git pull;
git commit -m "New release - ${TRAVIS_TAG}";
git push origin HEAD:master; 